# Generated by Django 3.1.7 on 2021-03-28 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210328_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinstance',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product'),
        ),
    ]
