# Generated by Django 3.1.7 on 2021-04-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210417_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='no description', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image_1',
            field=models.CharField(default='image_1', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=models.CharField(default='image_2', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image_3',
            field=models.CharField(default='image_3', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image_4',
            field=models.CharField(default='image_4', max_length=500),
            preserve_default=False,
        ),
    ]
