# Generated by Django 3.1.7 on 2021-03-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('b', 'buyer'), ('s', 'seller')], default='b', max_length=1),
        ),
    ]
